### ISSUE TITLE
400 Bad Request error when loading in a BibTex file

### ISSUE THREAD

**Issue by JacksonPageroth** [thomashirtz/notion-scholar#6]
Hi! I'm not sure what exactly I am doing wrong, but it seems like it isn't porting in the link for my Notion database URL. Any help would be appreciated! It also seems like the truncation issue that was talked about in a previous post is popping up here as well. Maybe it will still work if I fix the first issue, but just thought I should ask.

```
1/23: Publication(key="10.1039/c5ra11101c", title="{A review on natural surfactants}")
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notion_client/client.py", line 118, in _parse_response
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/pages'
For more information check: https://httpstatuses.com/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/ns", line 33, in <module>
    sys.exit(load_entry_point('notion-scholar==0.2.0', 'console_scripts', 'ns')())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notion_scholar/main.py", line 143, in main
    return run(**config_manager.get_run_kwargs())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notion_scholar/run.py", line 41, in run
    add_publications_to_database(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notion_scholar/notion_api.py", line 59, in add_publications_to_database
    client.pages.create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notion_client/api_endpoints.py", line 199, in create
    return self.parent.request(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notion_client/client.py", line 194, in request
    return self._parse_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notion_client/client.py", line 126, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: body failed validation: body.properties.Bibtex.rich_text[0].text.content.length should be ≤ `2000`, instead was `2071`.


```

**Comment by thomashirtz** [comment]
Can you put in the conversation the bibtex of the publication, so I can replicate the issue ? 

`1/23: Publication(key="10.1039/c5ra11101c", title="{A review on natural surfactants}")`

Also can you try to update notion-scholar to see if it fixes it ?

**Comment by JacksonPageroth** [comment]
Here's a link to the file: https://lists.papersapp.com/7RMuL8xbPpJc

**Comment by thomashirtz** [comment]
I committed some changes that should have fixed the issue, can you please let me know if everything is alright now ?

**Comment by JacksonPageroth** [comment]
Yup! Looks good, thanks a ton!
